/**
 * Manual bulk generation — "write me N posts between these two dates".
 *
 * This is an ORCHESTRATION layer and deliberately nothing else. It owns exactly
 * three things:
 *
 *   1. planning the slots the requested posts are scheduled into,
 *   2. calling the existing single-post generator once per slot,
 *   3. reporting honestly on what came out.
 *
 * Everything that makes a generated post good happens inside `generateDraftPost`
 * and is reached here for free, one call at a time: access control, the
 * "Content source" resolution, the atomic feed-item reservation that guarantees
 * one post per article, angle/pattern/aspect rotation, Topic Memory, the
 * Jaccard and semantic duplicate gates, language resolution, the frozen origin
 * snapshot, image generation, the source-article image import, embedding,
 * calibration and the audit log. None of it is re-implemented, re-ordered, or
 * bypassed — a bulk post is indistinguishable from a post the user generated by
 * clicking five times, apart from carrying a batch id.
 *
 * That sequential, one-at-a-time shape is a requirement, not an oversight. The
 * reservation, the duplicate gates and the diversity rotation all read what the
 * PREVIOUS post committed; generating concurrently would let five posts claim
 * five articles while every one of them still measures itself against the same
 * pre-run history, which is precisely how a batch of near-identical posts gets
 * written.
 *
 * Bulk posts are MANUAL generations: every one is created as `draft` and waits
 * for a person, whatever the channel's automation mode says. That is inherited
 * rather than asserted — `generateDraftPost` never passes an `initialStatus`, so
 * generation defaults to `draft`, and only cron's separate auto-approve step
 * ever promotes anything.
 *
 * A batch may also carry a CONTENT MIX — how many of its posts each source
 * writes. That too is orchestration and not a second distribution engine: the
 * quotas are handed to `lib/scheduling/content-mix.ts`, the same module the
 * weekly scheduler asks "which source is due next", and each answer becomes an
 * ordinary manual content-source pick on the very next generate call. The mix
 * arrives with the request and is never written back — the company's saved mix
 * is configuration, a batch's mix is one instruction.
 *
 * Running N generations inside one HTTP request is the real operational cost of
 * that shape, so the loop runs under the same ambient request deadline the cron
 * pipelines use and stops cleanly when the budget runs out — see
 * BULK_SOFT_BUDGET_MS.
 */

import { prisma } from "@/lib/db/client";
import type { SocialChannel } from "@prisma/client";
import {
  generateDraftPost,
  type GenerateDraftPostErrorCode,
  type GenerateDraftPostFailure,
} from "./generate-draft-post.service";
import type { ManualContentSourceRef } from "@/lib/ai/manual-content-source";
import { createAuditLog, AUDIT_ACTIONS } from "@/lib/services/audit/audit-log.service";
import {
  COMPANY_CONTENT_SOURCE_ID,
  nextDueQuota,
  type MixQuota,
} from "@/lib/scheduling/content-mix";
import {
  createRequestDeadline,
  remainingBudgetMs,
  runInRequestDeadline,
} from "@/lib/http/request-deadline";
import {
  MAX_BULK_POSTS,
  MAX_BULK_RANGE_DAYS,
  inclusiveDayCount,
  isStartDateInPast,
  planBulkSlots,
  planCustomSlots,
  validateCustomDistribution,
  type BulkCustomDay,
  type CustomDistributionError,
} from "@/lib/scheduling/bulk-schedule";

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface BulkGeneratePostsInput {
  channel: string;
  numberOfPosts: number;
  /** Inclusive `YYYY-MM-DD`, a business-zone calendar day. Must not be in the past. */
  startDate: string;
  /** Inclusive `YYYY-MM-DD`, a business-zone calendar day. */
  endDate: string;
  /**
   * A user-authored schedule: which days carry how many posts, and the exact
   * time of each one.
   *
   * Absent means "spread them evenly", the default — the channel's posting
   * windows inside the period decide both the days and the times. When present,
   * the user has chosen everything: the counts must add up to `numberOfPosts`,
   * and each day's times are scheduled exactly as given, in the business zone.
   * The channel's windows are not consulted at all in that case — a time on the
   * user's screen that this service then moved would make the form's preview a
   * lie. Either way the range bounds which days are allowed.
   */
  customDistribution?: BulkCustomDay[];

  // ── Everything below is passed through to each single generation unchanged ──
  contentLanguage?: string;
  includeSourceLinkOverride?: boolean;
  autoGenerateImageOverride?: boolean;
  llmConfigId?: string;
  /** The form's "Content source" choice, applied identically to every post. */
  contentSource?: ManualContentSourceRef;
  /**
   * A per-batch content mix: how many of these posts each source writes.
   *
   * Absent means the batch behaves exactly as it always has — one content-source
   * choice applied to every post. Present, it REPLACES that choice: each slot is
   * generated from whichever quota is due next, so `contentSource` must be the
   * pooled default (or absent) or the request is refused rather than one of the
   * two silently winning.
   *
   * This is a copy of the company's saved mix, sized to this batch, and nothing
   * here writes back to it. The saved default is configuration; this is one
   * run's instruction.
   */
  sourceMix?: BulkSourceQuota[];
}

/** One line of a per-batch content mix. */
export interface BulkSourceQuota {
  /** null = company content: written from the brand profile, with no article. */
  sourceId: string | null;
  /** How many posts of this batch this source writes. At least 1. */
  posts: number;
}

export interface BulkGeneratedPost {
  /** 1-based position of this post's slot in the batch. */
  index: number;
  postId: string;
  scheduledFor: Date;
}

/**
 * Why a slot could not be filled, grouped so a UI can say something useful
 * without knowing every generation error code:
 *
 *   • no_eligible_content — nothing left to write from (the pool is dry, or the
 *                           picked source is)
 *   • not_unique          — there was material, but no sufficiently different
 *                           post could be made from it
 *   • provider_error      — the LLM was unreachable, rate limited, or replied
 *                           with something unusable
 *   • configuration       — no usable model is configured for this generation
 *   • channel_limit       — the post plus its source URL exceeded the channel's
 *                           character limit
 *   • access              — the company/channel is not available to this user
 */
export type BulkFailureReason =
  | "no_eligible_content"
  | "not_unique"
  | "provider_error"
  | "configuration"
  | "channel_limit"
  | "access";

export interface BulkGenerationFailure {
  /** 1-based position of the slot this attempt was for. */
  index: number;
  /** The slot left empty by this failure. */
  scheduledFor: Date;
  code: GenerateDraftPostErrorCode;
  reason: BulkFailureReason;
  /** English, for logs and API consumers; the UI translates `code`. */
  message: string;
}

/**
 * Why a run ended before it had tried every slot.
 *
 *   • generation_failed — a slot failed; see `failures`.
 *   • time_budget       — too little of the request's wall-clock budget was left
 *                         to start another full generation. Not an error: the
 *                         posts already written are real and committed, and the
 *                         caller is told plainly that the rest were not tried.
 *   • mix_exhausted     — content-mix runs only: every source in the mix ran out
 *                         of material, so no quota was left that anything could
 *                         still be written from. Distinct from a plain failure
 *                         because no single slot failed — the batch simply ran
 *                         past what the company currently has to say.
 */
export type BulkStopReason = "generation_failed" | "time_budget" | "mix_exhausted";

export interface BulkGenerationSummary {
  /** Shared by every post this run wrote — also persisted on each of them. */
  batchId: string;
  requested: number;
  generated: number;
  /** Slots that produced no post: `failures.length + notAttempted`. */
  failed: number;
  postIds: string[];
  posts: BulkGeneratedPost[];
  /** One entry per slot that was attempted and failed. */
  failures: BulkGenerationFailure[];
  /** Slots never attempted, because the run stopped for `stopReason`. */
  notAttempted: number;
  /** True when the run ended before every slot was tried. */
  stoppedEarly: boolean;
  /** Null when every slot was attempted. */
  stopReason: BulkStopReason | null;
  /**
   * Content-mix runs only: the sources that ran out of material during this run,
   * in the order they did. Their unwritten posts were handed to the sources that
   * still had something (see transferExhaustedQuotas), so this is an account of
   * what happened rather than a list of failures — a batch can be complete and
   * still have entries here.
   *
   * Empty for a run without a mix, where a dry source ends the batch instead.
   */
  exhaustedSources: Array<string | null>;
}

/**
 * The two failure shapes are separate union members, discriminated by `code`, so
 * a caller that has ruled out the request-shape rejections is left holding a
 * plain `GenerateDraftPostFailure` — which is exactly what the shared HTTP
 * mapper takes. No re-wrapping, no widened error type at the route.
 */
export type BulkGeneratePostsResult =
  | { success: true; data: BulkGenerationSummary }
  // One member per code, not one member with a two-code union: a union-typed
  // discriminant cannot be narrowed AWAY, so the route's `else` would still be
  // holding these two and could not hand the rest to the shared mapper.
  | { success: false; code: "INVALID_POST_COUNT"; message: string }
  | { success: false; code: "INVALID_DATE_RANGE"; message: string }
  | { success: false; code: "START_DATE_IN_PAST"; message: string }
  | { success: false; code: "INVALID_DISTRIBUTION"; message: string }
  | { success: false; code: "INVALID_SOURCE_MIX"; message: string }
  | GenerateDraftPostFailure;

export interface BulkGeneratePostsDeps {
  /** The single-post pipeline. Injected in tests; never re-implemented. */
  generate?: typeof generateDraftPost;
  /** Reads the channel's posting windows so slots land at its usual hour. */
  loadPostingWindows?: (slug: string, channel: string) => Promise<unknown>;
  /** The company's enabled content-source ids — what a submitted mix is checked against. */
  loadEnabledSourceIds?: (slug: string) => Promise<Set<string>>;
  /** Batch id factory — injected so tests get a stable id. */
  newBatchId?: () => string;
  /** Writes the batch-level audit entry. Injected so tests can read it back. */
  auditLog?: typeof createAuditLog;
  /**
   * Wall clock, injected so the budget can be tested without waiting — and so
   * "is the start date in the past" has a fixed answer in tests.
   */
  now?: () => number;
  /** Overrides `BULK_SOFT_BUDGET_MS` for one run (tests). */
  softBudgetMs?: number;
  /** Overrides `MIN_SLOT_BUDGET_MS` for one run (tests). */
  minSlotBudgetMs?: number;
}

// ─── Time budget ───────────────────────────────────────────────────────────────

/**
 * Wall-clock budget for the whole bulk loop, under the route's `maxDuration`.
 *
 * N sequential generations in ONE request is the honest risk in this feature:
 * each post is an LLM call (up to three attempts), usually an image, and a
 * Cloudinary upload. Left alone, ten of those can outlast any platform function
 * cap — and a run killed by the cap is the worst possible outcome, because the
 * posts it already wrote ARE committed while the caller gets a connection reset
 * and never learns their ids.
 *
 * So the run installs the same ambient deadline the cron pipelines use
 * (`lib/http/request-deadline.ts`). Two effects, both already built and tested:
 *
 *   1. every outbound call — LLM, image worker, Cloudinary, embedding — takes
 *      its AbortSignal from the time still left, so no single hung call can eat
 *      the remaining headroom;
 *   2. the loop stops before starting a generation it cannot finish, and
 *      reports `time_budget`.
 *
 * The result is that running out of time degrades into the partial-success path
 * that already exists, rather than into a dropped request.
 *
 * 240s under a 300s cap leaves ~60s to write the summary and respond — the same
 * ratio the generation cron runs at.
 */
export const BULK_SOFT_BUDGET_MS = 240_000;

/**
 * Time that must remain before another generation is started.
 *
 * A generous single post (LLM plus image plus upload) fits in well under a
 * minute; starting one with less than this left would almost certainly buy an
 * aborted call and a spurious provider error instead of a post. The first slot
 * is always attempted regardless — a caller must never be told "no time" without
 * a single try.
 */
const MIN_SLOT_BUDGET_MS = 45_000;

// ─── Failure classification ────────────────────────────────────────────────────

/**
 * How a single generation failure is reported, and why every one of them ends
 * the run.
 *
 * Retrying inside a bulk run cannot help and can hurt:
 *
 *   • The pool is dry (NO_FEED_ITEMS_AVAILABLE / SELECTED_SOURCE_UNAVAILABLE) —
 *     nothing will have appeared a second later; only ingestion changes that.
 *   • The candidate stayed a duplicate (CANNOT_GENERATE_UNIQUE_POST) — the
 *     generator already exhausted its own retries, and it released the article
 *     it had claimed, so the next attempt would claim that same article (the
 *     reservation walks candidates in order) and re-run the same losing race.
 *   • The provider or the configuration is the problem — that is not going to
 *     be different for post 4 than it was for post 3, and each attempt spends
 *     real money and real time.
 *
 * So the rule is: attempt slots in order, stop at the first failure, and report
 * what was and was not written. The alternative — keep hammering until the
 * requested count is reached — is the one thing the feature must not do, since
 * every remaining route to that number produces a post the guards just rejected.
 */
export function classifyBulkFailure(code: GenerateDraftPostErrorCode): BulkFailureReason {
  switch (code) {
    case "NO_FEED_ITEMS_AVAILABLE":
    case "SELECTED_SOURCE_UNAVAILABLE":
      return "no_eligible_content";
    case "CANNOT_GENERATE_UNIQUE_POST":
      return "not_unique";
    case "LLM_RATE_LIMITED":
    case "LLM_PROVIDER_ERROR":
    case "LLM_RESPONSE_PARSE_ERROR":
      return "provider_error";
    case "NO_ACTIVE_PROVIDER":
    case "LLM_CONFIG_NOT_FOUND":
    case "PROVIDER_CONFIG_MISSING":
      return "configuration";
    case "POST_TOO_LONG_WITH_URL":
      return "channel_limit";
    case "NOT_FOUND":
    case "FORBIDDEN":
    case "INVALID_CHANNEL":
      return "access";
  }
}

/**
 * English wording for each way a custom distribution can be wrong.
 *
 * The form runs the very same `validateCustomDistribution` before it lets the
 * user submit, so in practice none of these are ever seen — they exist because
 * the server does not take the client's word for the schedule.
 */
const DISTRIBUTION_MESSAGES: Record<CustomDistributionError, string> = {
  empty: "Choose at least one date to publish on.",
  invalid_date: "One of the chosen dates is not a valid date.",
  duplicate_date: "The same date was listed more than once.",
  out_of_period: "Every chosen date must fall inside the start and end dates.",
  invalid_count: "Each chosen date must carry at least one whole post.",
  count_mismatch: "The posts assigned to the chosen dates must add up to the number requested.",
  invalid_time: "One of the chosen publishing times is not a valid time of day.",
  time_count_mismatch: "Each chosen date must have one publishing time per post assigned to it.",
  duplicate_slot: "Two posts were given the same date and time.",
  time_in_past: "Every chosen publishing time must be in the future.",
};

/** Fallback wording when the generator reported a code but no message. */
const DEFAULT_MESSAGES: Record<BulkFailureReason, string> = {
  no_eligible_content: "No unused source material is available to write another post from.",
  not_unique: "Could not write another post that is sufficiently different from recent ones.",
  provider_error: "The AI provider could not complete this generation.",
  configuration: "No usable AI model is configured for this generation.",
  channel_limit: "The generated post exceeded the channel's character limit.",
  access: "This company or channel is not available.",
};

// ─── Service ───────────────────────────────────────────────────────────────────

async function loadPostingWindowsFromDb(slug: string, channel: string): Promise<unknown> {
  // An unknown channel is not rejected here — generation is what owns that
  // answer (INVALID_CHANNEL), and it is reached one line later. This only has
  // to avoid handing Prisma a value its enum does not accept.
  const normalized = channel.toLowerCase();
  if (!isSocialChannel(normalized)) return null;

  // Scoped by slug only: the value is a time of day, and the generation call
  // right after this one is what enforces membership. A wrong answer here could
  // only mis-time posts that were never allowed to exist in the first place.
  const config = await prisma.channelConfig.findFirst({
    where: { company: { slug }, channel: normalized },
    select: { postingWindows: true },
  });
  return config?.postingWindows ?? null;
}

const SOCIAL_CHANNELS = ["facebook", "linkedin", "instagram", "tiktok"] as const;

function isSocialChannel(value: string): value is SocialChannel {
  return (SOCIAL_CHANNELS as readonly string[]).includes(value);
}

/**
 * The ids a per-batch mix may name: this company's ENABLED content sources.
 *
 * Scoped by slug only, on the same reasoning as the posting-windows read above —
 * these ids are only ever compared against what the request submitted, and the
 * generation call that follows is what enforces membership. Disabled sources are
 * excluded because the stored mix excludes them too (resolveContentMix drops
 * them), so a mix naming one is a stale client, not a valid instruction.
 */
async function loadEnabledSourceIdsFromDb(slug: string): Promise<Set<string>> {
  const rows = await prisma.contentSource.findMany({
    where: { company: { slug }, enabled: true },
    select: { id: true },
  });
  return new Set(rows.map((r) => r.id));
}

/**
 * Why a submitted per-batch mix cannot be run, in English, or null when it can.
 *
 * The form applies every one of these before it enables the button; they are
 * repeated here because the server does not take the client's word for where
 * posts come from. The sum rule is the load-bearing one: the mix IS the batch,
 * so a mix that does not add up to the number requested would silently generate
 * a different number of posts than the button promised.
 */
function validateSourceMix(
  mix: readonly BulkSourceQuota[],
  numberOfPosts: number,
  contentSource: ManualContentSourceRef | undefined,
  enabledSourceIds: ReadonlySet<string>
): string | null {
  // The two ways of choosing a source are alternatives, not layers: a specific
  // pick means "every post from here", a mix means "these posts from each of
  // these". Letting both through would leave the answer to whichever the loop
  // happened to read.
  if (contentSource !== undefined && contentSource.kind !== "company_rules") {
    return "A content mix and a single content source cannot both be chosen for one batch.";
  }

  if (mix.length === 0) {
    return "A content mix must name at least one source.";
  }

  const seen = new Set<string | null>();
  for (const quota of mix) {
    if (seen.has(quota.sourceId)) {
      return "The same content source is listed more than once in the mix.";
    }
    seen.add(quota.sourceId);

    if (!Number.isInteger(quota.posts) || quota.posts < 1) {
      return "Every source in the mix must be given a whole number of one post or more.";
    }

    if (quota.sourceId !== COMPANY_CONTENT_SOURCE_ID && !enabledSourceIds.has(quota.sourceId)) {
      return "The mix names a content source that does not exist or is not enabled.";
    }
  }

  const total = mix.reduce((sum, q) => sum + q.posts, 0);
  if (total !== numberOfPosts) {
    return `The content mix assigns ${total} posts but ${numberOfPosts} were requested.`;
  }

  return null;
}

/**
 * The content-source choice a mix quota stands for.
 *
 * Deliberately expressed as the ordinary manual selection rather than as a new
 * kind of instruction: a mix post is a manual generation from a picked source,
 * so it reaches the same resolution (`resolveManualContentSource`), the same
 * scope, and the same `Post.contentSourceId` attribution as if the user had
 * chosen that source in the dropdown themselves. The company-content quota maps
 * to the mission sentinel, which is what the weekly scheduler's own mix path
 * scopes to for a null source id.
 */
function contentSourceForQuota(sourceId: string | null): ManualContentSourceRef {
  return sourceId === COMPANY_CONTENT_SOURCE_ID
    ? { kind: "company_mission" }
    : { kind: "source", sourceId };
}

/**
 * Generates up to `numberOfPosts` drafts, one per planned slot, stopping at the
 * first failure.
 *
 * Partial success is the normal outcome, not an error: three posts written out
 * of five requested is three real posts plus an honest account of why the other
 * two are missing. The only case reported as an outright failure is a run that
 * produced NOTHING — there the caller learns exactly what a single generation
 * would have told it, with the same code, so the API answers identically
 * whether one post or five were asked for.
 */
export async function bulkGeneratePosts(
  slug: string,
  userId: string,
  isGlobalAdmin: boolean,
  input: BulkGeneratePostsInput,
  deps: BulkGeneratePostsDeps = {}
): Promise<BulkGeneratePostsResult> {
  const generate = deps.generate ?? generateDraftPost;
  const loadPostingWindows = deps.loadPostingWindows ?? loadPostingWindowsFromDb;
  const loadEnabledSourceIds = deps.loadEnabledSourceIds ?? loadEnabledSourceIdsFromDb;
  const newBatchId = deps.newBatchId ?? (() => crypto.randomUUID());
  const auditLog = deps.auditLog ?? createAuditLog;
  const now = deps.now ?? Date.now;

  // ── Validate the request itself ───────────────────────────────────────────
  // Before any access check, because these are answers about the request, not
  // about the company — and they cost nothing to give.
  if (
    !Number.isInteger(input.numberOfPosts) ||
    input.numberOfPosts < 1 ||
    input.numberOfPosts > MAX_BULK_POSTS
  ) {
    return {
      success: false,
      code: "INVALID_POST_COUNT",
      message: `Number of posts must be a whole number between 1 and ${MAX_BULK_POSTS}.`,
    };
  }

  if (inclusiveDayCount(input.startDate, input.endDate) === null) {
    return {
      success: false,
      code: "INVALID_DATE_RANGE",
      message: `The end date must be a valid date on or after the start date, and at most ${MAX_BULK_RANGE_DAYS} days later.`,
    };
  }

  // A period that has already begun would schedule posts into the past, and a
  // post scheduled into the past is one the publisher will refuse to fire — so
  // it is refused here, where it is still a request rather than a batch of
  // stranded drafts. The form applies the same rule to its own date input.
  if (isStartDateInPast(input.startDate, new Date(now()))) {
    return {
      success: false,
      code: "START_DATE_IN_PAST",
      message: "The start date must be today or later.",
    };
  }

  const custom = input.customDistribution;
  if (custom !== undefined) {
    const problem = validateCustomDistribution(
      custom,
      input.numberOfPosts,
      input.startDate,
      input.endDate,
      new Date(now())
    );
    if (problem !== null) {
      return {
        success: false,
        code: "INVALID_DISTRIBUTION",
        message: DISTRIBUTION_MESSAGES[problem],
      };
    }
  }

  // The per-batch content mix, checked against the company's real sources before
  // anything is generated. An unknown id is refused rather than skipped: it would
  // otherwise fail per-slot, be read as "that source is spent", and quietly move
  // its posts onto sources the user never allocated them to.
  const mixQuotas: MixQuota[] | null =
    input.sourceMix === undefined
      ? null
      : input.sourceMix.map((q) => ({ sourceId: q.sourceId, postsPerWeek: q.posts }));

  if (input.sourceMix !== undefined) {
    const problem = validateSourceMix(
      input.sourceMix,
      input.numberOfPosts,
      input.contentSource,
      await loadEnabledSourceIds(slug)
    );
    if (problem !== null) {
      return { success: false, code: "INVALID_SOURCE_MIX", message: problem };
    }
  }

  // Slots are planned up front because each post is persisted with its own
  // `scheduledFor` as it is written.
  //
  //   • Evenly — the dates bound the PERIOD and the channel's posting windows
  //     inside it decide the days and the times. Those are read from the database
  //     rather than taken from the request: the client previews with a copy of
  //     them, it does not get to set them.
  //   • Custom — the user chose every date and every time, already checked
  //     against that same period and against the clock. They are scheduled
  //     verbatim, and the windows are not loaded at all, because consulting them
  //     here could only move a post off the time the form promised.
  const slots =
    custom !== undefined
      ? planCustomSlots(custom)
      : planBulkSlots({
          startDate: input.startDate,
          endDate: input.endDate,
          count: input.numberOfPosts,
          postingWindows: await loadPostingWindows(slug, input.channel),
        });

  const batchId = newBatchId();
  const posts: BulkGeneratedPost[] = [];
  const failures: BulkGenerationFailure[] = [];
  let stopReason: BulkStopReason | null = null;
  // Taken from the first post actually written rather than looked up: the batch
  // audit entry only exists when something was generated, and generation has
  // already resolved the company by then.
  let companyId: string | null = null;

  // Mix bookkeeping, all of it scoped to THIS run. `generatedBySource` is what
  // nextDueQuota measures a quota's progress against; `exhausted` is what makes
  // transferExhaustedQuotas hand a dry source's remaining posts to the sources
  // that can still write them. Neither is persisted — the saved mix is untouched
  // by anything that happens in this loop.
  const generatedBySource = new Map<string | null, number>();
  const exhausted = new Set<string | null>();
  const exhaustedSources: Array<string | null> = [];

  const minSlotBudgetMs = deps.minSlotBudgetMs ?? MIN_SLOT_BUDGET_MS;
  const deadline = createRequestDeadline(now() + (deps.softBudgetMs ?? BULK_SOFT_BUDGET_MS), now);

  // Everything below runs under the ambient deadline, so every outbound call the
  // generations make is bounded by the time left in THIS request. See
  // BULK_SOFT_BUDGET_MS for why a bulk run cannot be allowed to find out about
  // the function cap the hard way.
  const zeroGenerated = await runInRequestDeadline(deadline, async () => {
    /** The single-post answer for a run that wrote nothing at all. */
    const asSingleFailure = (result: GenerateDraftPostFailure) => ({
      success: false as const,
      code: result.code,
      message: result.message ?? DEFAULT_MESSAGES[classifyBulkFailure(result.code)],
      reason: result.reason,
      attempts: result.attempts,
      retryAfterMs: result.retryAfterMs,
    });

    // The last "nothing left to write from" a mix run hit. Kept because it is
    // the honest answer when every source runs dry before a single post exists:
    // the caller gets the generation's own code, exactly as it would from a
    // one-post request that found the same empty pool.
    let lastExhaustion: GenerateDraftPostFailure | null = null;

    for (let i = 0; i < slots.length; i++) {
      const scheduledFor = slots[i];

      // Never start a generation there is not enough time left to finish; the
      // first slot is always attempted, so a run can never report "no time"
      // without having tried at all.
      if (i > 0 && remainingBudgetMs() < minSlotBudgetMs) {
        stopReason = "time_budget";
        break;
      }

      // Fill this one slot.
      //
      // Without a mix that is a single attempt, exactly as before. With one, a
      // slot may be attempted more than once: a source that turns out to have
      // nothing left is marked spent for the rest of the run and its remaining
      // posts pass to the sources that can still write them (nextDueQuota reads
      // the post-transfer quotas), so the slot is retried against whichever
      // source is due next rather than costing the batch a post. Every other
      // kind of failure still ends the run at the first one — see
      // classifyBulkFailure for why retrying those cannot help.
      let stop = false;

      while (!stop) {
        const due =
          mixQuotas === null
            ? null
            : nextDueQuota({ quotas: mixQuotas, generatedBySource, exhausted });

        // Mix runs only: every quota is filled or spent, so there is nothing
        // left to write this slot — or any slot after it — from.
        if (mixQuotas !== null && due === null) {
          if (posts.length === 0 && lastExhaustion !== null) {
            return asSingleFailure(lastExhaustion);
          }
          stopReason = "mix_exhausted";
          stop = true;
          break;
        }

        // The one and only generation path — the same call the single-post route
        // makes, with the same options, plus this post's slot and batch id. A
        // mix post differs only in WHICH source it names, and it names it the
        // same way the dropdown would.
        const result = await generate(slug, input.channel, userId, isGlobalAdmin, {
          contentLanguage: input.contentLanguage,
          includeSourceLinkOverride: input.includeSourceLinkOverride,
          autoGenerateImageOverride: input.autoGenerateImageOverride,
          llmConfigId: input.llmConfigId,
          contentSource: due === null ? input.contentSource : contentSourceForQuota(due.sourceId),
          scheduledFor,
          generationBatchId: batchId,
        });

        if (result.success) {
          companyId ??= result.post.companyId;
          posts.push({ index: i + 1, postId: result.post.id, scheduledFor });
          if (due !== null) {
            generatedBySource.set(due.sourceId, (generatedBySource.get(due.sourceId) ?? 0) + 1);
          }
          break;
        }

        const reason = classifyBulkFailure(result.code);

        // This source is spent. Not a failure of the slot — the posts it owed
        // move to the sources that still have material, and this slot is tried
        // again against the next one due.
        if (due !== null && reason === "no_eligible_content") {
          exhausted.add(due.sourceId);
          exhaustedSources.push(due.sourceId);
          lastExhaustion = result;
          continue;
        }

        // Nothing was written at all: answer exactly as the single-post flow
        // would, so the caller gets the real code (and its retry hints) rather
        // than a "successful batch of zero".
        if (posts.length === 0) return asSingleFailure(result);

        failures.push({
          index: i + 1,
          scheduledFor,
          code: result.code,
          reason,
          message: result.message ?? DEFAULT_MESSAGES[reason],
        });
        stopReason = "generation_failed";
        stop = true;
      }

      if (stop) break;
    }

    return null;
  });

  if (zeroGenerated !== null) return zeroGenerated;

  const attempted = posts.length + failures.length;
  const notAttempted = input.numberOfPosts - attempted;

  if (posts.length < input.numberOfPosts) {
    console.warn(
      `[bulk-generate] Batch ${batchId} produced ${posts.length}/${input.numberOfPosts} posts` +
        (failures.length > 0
          ? ` — stopped at slot ${failures[0].index}: ${failures[0].code}`
          : stopReason === "time_budget"
            ? " — stopped: request time budget exhausted"
            : stopReason === "mix_exhausted"
              ? " — stopped: every source in the content mix ran out of material"
              : "")
    );
  }

  // One entry for the whole request, beside the per-post POST_GENERATED entries
  // generation already writes. Those record what each post is; this records the
  // decision that produced them — how many were asked for, over which period,
  // how they were distributed, and where the run stopped if it did. Without it
  // the batch id in the posts table has nothing explaining what it refers to,
  // and a partial run leaves no trace at all once the HTTP response is gone.
  if (companyId !== null) {
    await auditLog({
      companyId,
      userId,
      action: AUDIT_ACTIONS.POST_BULK_GENERATED,
      entityType: "post_batch",
      entityId: batchId,
      metadata: {
        channel: input.channel,
        requested: input.numberOfPosts,
        generated: posts.length,
        failed: input.numberOfPosts - posts.length,
        distribution: custom !== undefined ? "custom" : "even",
        startDate: input.startDate,
        endDate: input.endDate,
        // The window the batch actually occupies, which is what a reader wants
        // when asking "what did this click put on the calendar?".
        firstScheduledFor: posts[0]?.scheduledFor.toISOString() ?? null,
        lastScheduledFor: posts[posts.length - 1]?.scheduledFor.toISOString() ?? null,
        stopReason,
        failureCode: failures[0]?.code ?? null,
        postIds: posts.map((p) => p.postId),
        // The mix this ONE run used, recorded because it may differ from the
        // company's saved default — which this run did not change. Without it
        // the log could not explain why these posts came from these sources.
        sourceMix: input.sourceMix ?? null,
        exhaustedSources,
      },
    });
  }

  return {
    success: true,
    data: {
      batchId,
      requested: input.numberOfPosts,
      generated: posts.length,
      failed: input.numberOfPosts - posts.length,
      postIds: posts.map((p) => p.postId),
      posts,
      failures,
      notAttempted,
      stoppedEarly: attempted < input.numberOfPosts,
      stopReason,
      exhaustedSources,
    },
  };
}
