/**
 * Manual bulk generation — "write me N posts between these two dates".
 *
 * This is an ORCHESTRATION layer and deliberately nothing else. It owns exactly
 * three things:
 *
 *   1. planning the slots the requested posts are scheduled into,
 *   2. calling the existing single-post generator once per slot,
 *   3. reporting honestly on what came out.
 *
 * Everything that makes a generated post good happens inside `generateDraftPost`
 * and is reached here for free, one call at a time: access control, the
 * "Content source" resolution, the atomic feed-item reservation that guarantees
 * one post per article, angle/pattern/aspect rotation, Topic Memory, the
 * Jaccard and semantic duplicate gates, language resolution, the frozen origin
 * snapshot, image generation, the source-article image import, embedding,
 * calibration and the audit log. None of it is re-implemented, re-ordered, or
 * bypassed — a bulk post is indistinguishable from a post the user generated by
 * clicking five times, apart from carrying a batch id.
 *
 * That sequential, one-at-a-time shape is a requirement, not an oversight. The
 * reservation, the duplicate gates and the diversity rotation all read what the
 * PREVIOUS post committed; generating concurrently would let five posts claim
 * five articles while every one of them still measures itself against the same
 * pre-run history, which is precisely how a batch of near-identical posts gets
 * written.
 *
 * Bulk posts are MANUAL generations: every one is created as `draft` and waits
 * for a person, whatever the channel's automation mode says. That is inherited
 * rather than asserted — `generateDraftPost` never passes an `initialStatus`, so
 * generation defaults to `draft`, and only cron's separate auto-approve step
 * ever promotes anything.
 *
 * A batch may also carry a CONTENT MIX — how many of its posts each source
 * writes. That too is orchestration and not a second distribution engine: the
 * quotas are handed to `lib/scheduling/content-mix.ts`, the same module the
 * weekly scheduler asks "which source is due next", and each answer becomes an
 * ordinary manual content-source pick on the very next generate call. The mix
 * arrives with the request and is never written back — the company's saved mix
 * is configuration, a batch's mix is one instruction.
 *
 * Running N generations inside one HTTP request is the real operational cost of
 * that shape, so the loop runs under the same ambient request deadline the cron
 * pipelines use and stops cleanly when the budget runs out — see
 * BULK_SOFT_BUDGET_MS.
 */

import { prisma } from "@/lib/db/client";
import type { SocialChannel } from "@prisma/client";
import {
  generateDraftPost,
  type GenerateDraftPostErrorCode,
  type GenerateDraftPostFailure,
  type UniquenessFailureReason,
} from "./generate-draft-post.service";
import {
  generateTopicAcrossChannels,
  type TopicAnchor,
  type TopicGenerationOutcome,
} from "./generate-topic-across-channels.service";
import type { ManualContentSourceRef } from "@/lib/ai/manual-content-source";
import { createAuditLog, AUDIT_ACTIONS } from "@/lib/services/audit/audit-log.service";
import {
  COMPANY_CONTENT_SOURCE_ID,
  nextDueQuota,
  type MixQuota,
} from "@/lib/scheduling/content-mix";
import {
  createRequestDeadline,
  remainingBudgetMs,
  runInRequestDeadline,
} from "@/lib/http/request-deadline";
import { planBulkSlots, planCustomSlots, type BulkCustomDay } from "@/lib/scheduling/bulk-schedule";
import {
  validateBulkRequest,
  type BulkRequestErrorCode,
  type BulkSourceQuota,
} from "./validate-bulk-request.service";

export type { BulkSourceQuota };

// ─── Types ─────────────────────────────────────────────────────────────────────

export interface BulkGeneratePostsInput {
  /**
   * Every channel each topic is written for, in attempt order.
   *
   * The count below is TOPICS, not posts: 5 topics × 3 channels is 5 content
   * groups and 15 Post rows. One channel is the ordinary case and behaves
   * exactly as a single-channel batch always has.
   */
  channels: readonly string[];
  /** How many content TOPICS to write. Each one becomes a content group. */
  numberOfPosts: number;
  /** Inclusive `YYYY-MM-DD`, a business-zone calendar day. Must not be in the past. */
  startDate: string;
  /** Inclusive `YYYY-MM-DD`, a business-zone calendar day. */
  endDate: string;
  /**
   * A user-authored schedule: which days carry how many posts, and the exact
   * time of each one.
   *
   * Absent means "spread them evenly", the default — the channel's posting
   * windows inside the period decide both the days and the times. When present,
   * the user has chosen everything: the counts must add up to `numberOfPosts`,
   * and each day's times are scheduled exactly as given, in the business zone.
   * The channel's windows are not consulted at all in that case — a time on the
   * user's screen that this service then moved would make the form's preview a
   * lie. Either way the range bounds which days are allowed.
   */
  customDistribution?: BulkCustomDay[];

  // ── Everything below is passed through to each single generation unchanged ──
  contentLanguage?: string;
  includeSourceLinkOverride?: boolean;
  autoGenerateImageOverride?: boolean;
  llmConfigId?: string;
  /** The form's "Content source" choice, applied identically to every post. */
  contentSource?: ManualContentSourceRef;
  /**
   * A per-batch content mix: how many of these posts each source writes.
   *
   * Absent means the batch behaves exactly as it always has — one content-source
   * choice applied to every post. Present, it REPLACES that choice: each slot is
   * generated from whichever quota is due next, so `contentSource` must be the
   * pooled default (or absent) or the request is refused rather than one of the
   * two silently winning.
   *
   * This is a copy of the company's saved mix, sized to this batch, and nothing
   * here writes back to it. The saved default is configuration; this is one
   * run's instruction.
   */
  sourceMix?: BulkSourceQuota[];
}

export interface BulkGeneratedPost {
  /** 1-based position of this post's TOPIC in the batch. */
  index: number;
  postId: string;
  scheduledFor: Date;
  /** Which channel this version was written for. */
  channel: string;
  /** The content group it belongs to — its siblings share this id. */
  contentGroupId: string;
}

/**
 * One content topic's outcome: the channel versions that exist and the ones that
 * do not.
 *
 * A group with some of each is a normal result, not a broken one — the posts
 * that exist are real drafts. It is reported rather than smoothed over so the UI
 * can say "Facebook and LinkedIn were written, Instagram was not, because …"
 * instead of quietly presenting a group of two as the group of three that was
 * asked for.
 */
export interface BulkGeneratedGroup {
  /** 1-based position of this topic in the batch. */
  index: number;
  contentGroupId: string;
  posts: BulkGeneratedPost[];
  failures: BulkGenerationFailure[];
}

/**
 * Why a slot could not be filled, grouped so a UI can say something useful
 * without knowing every generation error code:
 *
 *   • no_eligible_content — nothing left to write from (the pool is dry, or the
 *                           picked source is)
 *   • not_unique          — there was material, but no sufficiently different
 *                           post could be made from it
 *   • provider_error      — the LLM was unreachable, rate limited, or replied
 *                           with something unusable
 *   • configuration       — no usable model is configured for this generation
 *   • channel_limit       — the post plus its source URL exceeded the channel's
 *                           character limit
 *   • access              — the company/channel is not available to this user
 */
export type BulkFailureReason =
  | "no_eligible_content"
  | "not_unique"
  | "provider_error"
  | "configuration"
  | "channel_limit"
  | "access";

export interface BulkGenerationFailure {
  /** 1-based position of the TOPIC this attempt was for. */
  index: number;
  /** The slot left empty by this failure. */
  scheduledFor: Date;
  code: GenerateDraftPostErrorCode;
  /**
   * The coarse grouping above — NOT the generator's own `reason`, which is a
   * uniqueness-guard name and is carried separately as `uniquenessReason`. The
   * two have always been different things; they are kept under different names
   * so neither has to be renamed to make room for the other.
   */
  reason: BulkFailureReason;
  /** English, for logs and API consumers; the UI translates `code`. */
  message: string;
  /** The channel version that could not be written. */
  channel: string;

  // ── The generator's own diagnostics, verbatim ──────────────────────────────
  // Present only when the underlying failure carried them. A partial batch used
  // to be able to lose these — a rate-limited channel would report the code and
  // nothing about how long to wait — so they are threaded through rather than
  // left to the zero-generated path to be the only one that has them.

  /** CANNOT_GENERATE_UNIQUE_POST only: which guard forced the abort. */
  uniquenessReason?: UniquenessFailureReason;
  /** CANNOT_GENERATE_UNIQUE_POST only: attempts made before aborting. */
  attempts?: number;
  /** LLM_RATE_LIMITED only, and only when the provider advertised a wait. */
  retryAfterMs?: number;
}

/**
 * Why a run ended before it had tried every slot.
 *
 *   • generation_failed — a slot failed; see `failures`.
 *   • time_budget       — too little of the request's wall-clock budget was left
 *                         to start another full generation. Not an error: the
 *                         posts already written are real and committed, and the
 *                         caller is told plainly that the rest were not tried.
 *   • mix_exhausted     — content-mix runs only: every source in the mix ran out
 *                         of material, so no quota was left that anything could
 *                         still be written from. Distinct from a plain failure
 *                         because no single slot failed — the batch simply ran
 *                         past what the company currently has to say.
 */
export type BulkStopReason = "generation_failed" | "time_budget" | "mix_exhausted";

export interface BulkGenerationSummary {
  /** Shared by every post this run wrote — also persisted on each of them. */
  batchId: string;
  /** Topics asked for. NOT post rows: see `requestedPosts`. */
  requested: number;
  /** Topics that produced at least one channel version. */
  generated: number;
  /** Topics that produced no post at all: `failures.length + notAttempted`. */
  failed: number;
  /** The channels every topic was asked for, echoed so a reader can do the maths. */
  channels: string[];
  /** `requested × channels.length` — the Post rows a complete run would write. */
  requestedPosts: number;
  /** Post rows actually written, across every topic and channel. */
  generatedPosts: number;
  /** One entry per topic that was attempted, complete or partial. */
  groups: BulkGeneratedGroup[];
  postIds: string[];
  posts: BulkGeneratedPost[];
  /** One entry per slot that was attempted and failed. */
  failures: BulkGenerationFailure[];
  /** Slots never attempted, because the run stopped for `stopReason`. */
  notAttempted: number;
  /** True when the run ended before every slot was tried. */
  stoppedEarly: boolean;
  /** Null when every slot was attempted. */
  stopReason: BulkStopReason | null;
  /**
   * Content-mix runs only: the sources that ran out of material during this run,
   * in the order they did. Their unwritten posts were handed to the sources that
   * still had something (see transferExhaustedQuotas), so this is an account of
   * what happened rather than a list of failures — a batch can be complete and
   * still have entries here.
   *
   * Empty for a run without a mix, where a dry source ends the batch instead.
   */
  exhaustedSources: Array<string | null>;
  /**
   * The topic currently being written, present only on a MID-FLIGHT summary.
   *
   * Two jobs. It is what the UI shows as "writing topic 3 of 5", and it is what
   * a retry resumes from: the anchor here is the story this group settled on, so
   * the channels still missing continue it rather than each deciding a new one.
   * Absent from a finished summary, where every topic is in `groups`.
   */
  liveTopic?: {
    index: number;
    contentGroupId: string;
    anchor: TopicAnchor | null;
    completedChannels: string[];
  };
}

/**
 * The two failure shapes are separate union members, discriminated by `code`, so
 * a caller that has ruled out the request-shape rejections is left holding a
 * plain `GenerateDraftPostFailure` — which is exactly what the shared HTTP
 * mapper takes. No re-wrapping, no widened error type at the route.
 */
export type BulkGeneratePostsResult =
  | { success: true; data: BulkGenerationSummary }
  // One member per code, not one member with a five-code union: a union-typed
  // discriminant cannot be narrowed AWAY, so the route's `else` would still be
  // holding these and could not hand the rest to the shared mapper.
  | { success: false; code: "INVALID_POST_COUNT"; message: string }
  | { success: false; code: "INVALID_DATE_RANGE"; message: string }
  | { success: false; code: "START_DATE_IN_PAST"; message: string }
  | { success: false; code: "INVALID_DISTRIBUTION"; message: string }
  | { success: false; code: "INVALID_SOURCE_MIX"; message: string }
  | GenerateDraftPostFailure;

/**
 * Widens a request-shape problem back into the service's result union.
 *
 * The union above spells each code out separately so a route can narrow them
 * away one at a time; `BulkRequestProblem` carries the code as a single field.
 * The cast bridges exactly that difference and nothing else — the codes are the
 * same five, checked by the type below.
 */
function asRequestFailure(problem: {
  code: BulkRequestErrorCode;
  message: string;
}): Extract<BulkGeneratePostsResult, { code: BulkRequestErrorCode }> {
  return { success: false, ...problem } as Extract<
    BulkGeneratePostsResult,
    { code: BulkRequestErrorCode }
  >;
}

/**
 * What a previous attempt of this same batch already committed.
 *
 * A bulk run can be interrupted — the worker's lease can be lost, the process
 * can be restarted, the queue can retry the job. Re-running the whole batch
 * would write a second copy of everything it had already finished, which is both
 * a duplicate-content bug and real money spent twice. So a resumed attempt is
 * handed what exists and generates only the remainder.
 *
 * Keyed by topic index (1-based, matching `BulkGeneratedGroup.index`) so it
 * lines up with the deterministic plan rather than with any id the retry would
 * have to re-derive.
 */
export interface BulkResumeState {
  /** Topic index → the group id that topic was given on the first attempt. */
  contentGroupIds: Readonly<Record<number, string>>;
  /** Topic index → channels already committed for it. */
  completedChannels: Readonly<Record<number, readonly string[]>>;
  /**
   * Topic index → the topic it settled on. This is what makes a resumed sibling
   * continue the SAME story: without it the channels still missing would each
   * decide a topic of their own and the group would fragment.
   */
  anchors: Readonly<Record<number, TopicAnchor>>;
  /** Post ids already written, so the summary counts them without a re-query. */
  posts: readonly BulkGeneratedPost[];
}

export interface BulkGeneratePostsDeps {
  /** The single-post pipeline. Injected in tests; never re-implemented. */
  generate?: typeof generateDraftPost;
  /** The per-topic fan-out. Injected in tests; never re-implemented. */
  generateTopic?: typeof generateTopicAcrossChannels;
  /**
   * Called after every topic, with the summary as it stands. The queue job uses
   * it to persist progress, which is both what the UI polls and what a retry
   * resumes from. Best-effort by contract — it must never throw.
   */
  onProgress?: (summary: BulkGenerationSummary) => Promise<void>;
  /** What an earlier attempt of this batch already wrote. */
  resume?: BulkResumeState;
  /** Reads the channel's posting windows so slots land at its usual hour. */
  loadPostingWindows?: (slug: string, channel: string) => Promise<unknown>;
  /** The company's enabled content-source ids — what a submitted mix is checked against. */
  loadEnabledSourceIds?: (slug: string) => Promise<Set<string>>;
  /** Batch id factory — injected so tests get a stable id. */
  newBatchId?: () => string;
  /**
   * Content-group id factory, one call per topic. Injected so tests get stable
   * ids; the queue job supplies ids from its persisted plan so a retry keeps the
   * groups it already created.
   */
  newContentGroupId?: () => string;
  /** Writes the batch-level audit entry. Injected so tests can read it back. */
  auditLog?: typeof createAuditLog;
  /**
   * Wall clock, injected so the budget can be tested without waiting — and so
   * "is the start date in the past" has a fixed answer in tests.
   */
  now?: () => number;
  /** Overrides `BULK_SOFT_BUDGET_MS` for one run (tests). */
  softBudgetMs?: number;
  /** Overrides `MIN_SLOT_BUDGET_MS` for one run (tests). */
  minSlotBudgetMs?: number;
}

// ─── Time budget ───────────────────────────────────────────────────────────────

/**
 * Wall-clock budget for the whole bulk loop, under the route's `maxDuration`.
 *
 * N sequential generations in ONE request is the honest risk in this feature:
 * each post is an LLM call (up to three attempts), usually an image, and a
 * Cloudinary upload. Left alone, ten of those can outlast any platform function
 * cap — and a run killed by the cap is the worst possible outcome, because the
 * posts it already wrote ARE committed while the caller gets a connection reset
 * and never learns their ids.
 *
 * So the run installs the same ambient deadline the cron pipelines use
 * (`lib/http/request-deadline.ts`). Two effects, both already built and tested:
 *
 *   1. every outbound call — LLM, image worker, Cloudinary, embedding — takes
 *      its AbortSignal from the time still left, so no single hung call can eat
 *      the remaining headroom;
 *   2. the loop stops before starting a generation it cannot finish, and
 *      reports `time_budget`.
 *
 * The result is that running out of time degrades into the partial-success path
 * that already exists, rather than into a dropped request.
 *
 * 240s under a 300s cap leaves ~60s to write the summary and respond — the same
 * ratio the generation cron runs at.
 */
export const BULK_SOFT_BUDGET_MS = 240_000;

/**
 * FLOOR for the time that must remain before another TOPIC is started.
 *
 * A floor, not the threshold itself — the threshold is measured (see
 * `observedSlotMs` in the loop). This value only covers the case where there is
 * no measurement worth trusting yet, such as a first topic that failed in
 * seconds.
 *
 * It is deliberately no longer the whole answer. A fixed 45s rested on the claim
 * that "a generous single post fits in well under a minute", and that claim is
 * false wherever images are generated by a self-hosted worker: one CHANNEL was
 * measured at ~158s there, and a topic is that times the channels asked for. A
 * threshold three and a half times too small does not merely mistime a run — it
 * admits a topic that can start but not finish, and what gets dropped is not the
 * topic but the image inside it, silently, because the LLM call runs first and
 * takes whatever budget is left while the image work is best-effort and has
 * nowhere to report to. The same mistake, one layer up, that
 * `MIN_CHANNEL_BUDGET_MS` documents in the orchestrator.
 *
 * The first slot is always attempted regardless — a caller must never be told
 * "no time" without a single try.
 */
const MIN_SLOT_BUDGET_MS = 45_000;

// ─── Failure classification ────────────────────────────────────────────────────

/**
 * How a single generation failure is reported, and why every one of them ends
 * the run.
 *
 * Retrying inside a bulk run cannot help and can hurt:
 *
 *   • The pool is dry (NO_FEED_ITEMS_AVAILABLE / SELECTED_SOURCE_UNAVAILABLE) —
 *     nothing will have appeared a second later; only ingestion changes that.
 *   • The candidate stayed a duplicate (CANNOT_GENERATE_UNIQUE_POST) — the
 *     generator already exhausted its own retries, and it released the article
 *     it had claimed, so the next attempt would claim that same article (the
 *     reservation walks candidates in order) and re-run the same losing race.
 *   • The provider or the configuration is the problem — that is not going to
 *     be different for post 4 than it was for post 3, and each attempt spends
 *     real money and real time.
 *
 * So the rule is: attempt slots in order, stop at the first failure, and report
 * what was and was not written. The alternative — keep hammering until the
 * requested count is reached — is the one thing the feature must not do, since
 * every remaining route to that number produces a post the guards just rejected.
 */
export function classifyBulkFailure(code: GenerateDraftPostErrorCode): BulkFailureReason {
  switch (code) {
    case "NO_FEED_ITEMS_AVAILABLE":
    case "SELECTED_SOURCE_UNAVAILABLE":
      return "no_eligible_content";
    case "CANNOT_GENERATE_UNIQUE_POST":
      return "not_unique";
    case "LLM_RATE_LIMITED":
    case "LLM_PROVIDER_ERROR":
    case "LLM_RESPONSE_PARSE_ERROR":
      return "provider_error";
    case "NO_ACTIVE_PROVIDER":
    case "LLM_CONFIG_NOT_FOUND":
    case "PROVIDER_CONFIG_MISSING":
      return "configuration";
    case "POST_TOO_LONG_WITH_URL":
      return "channel_limit";
    case "NOT_FOUND":
    case "FORBIDDEN":
    case "INVALID_CHANNEL":
      return "access";
  }
}

/** Fallback wording when the generator reported a code but no message. */
const DEFAULT_MESSAGES: Record<BulkFailureReason, string> = {
  no_eligible_content: "No unused source material is available to write another post from.",
  not_unique: "Could not write another post that is sufficiently different from recent ones.",
  provider_error: "The AI provider could not complete this generation.",
  configuration: "No usable AI model is configured for this generation.",
  channel_limit: "The generated post exceeded the channel's character limit.",
  access: "This company or channel is not available.",
};

// ─── Service ───────────────────────────────────────────────────────────────────

async function loadPostingWindowsFromDb(slug: string, channel: string): Promise<unknown> {
  // An unknown channel is not rejected here — generation is what owns that
  // answer (INVALID_CHANNEL), and it is reached one line later. This only has
  // to avoid handing Prisma a value its enum does not accept.
  const normalized = channel.toLowerCase();
  if (!isSocialChannel(normalized)) return null;

  // Scoped by slug only: the value is a time of day, and the generation call
  // right after this one is what enforces membership. A wrong answer here could
  // only mis-time posts that were never allowed to exist in the first place.
  const config = await prisma.channelConfig.findFirst({
    where: { company: { slug }, channel: normalized },
    select: { postingWindows: true },
  });
  return config?.postingWindows ?? null;
}

const SOCIAL_CHANNELS = ["facebook", "linkedin", "instagram", "tiktok"] as const;

function isSocialChannel(value: string): value is SocialChannel {
  return (SOCIAL_CHANNELS as readonly string[]).includes(value);
}

/**
 * The content-source choice a mix quota stands for.
 *
 * Deliberately expressed as the ordinary manual selection rather than as a new
 * kind of instruction: a mix post is a manual generation from a picked source,
 * so it reaches the same resolution (`resolveManualContentSource`), the same
 * scope, and the same `Post.contentSourceId` attribution as if the user had
 * chosen that source in the dropdown themselves. The company-content quota maps
 * to the mission sentinel, which is what the weekly scheduler's own mix path
 * scopes to for a null source id.
 */
function contentSourceForQuota(sourceId: string | null): ManualContentSourceRef {
  return sourceId === COMPANY_CONTENT_SOURCE_ID
    ? { kind: "company_mission" }
    : { kind: "source", sourceId };
}

/**
 * Generates up to `numberOfPosts` drafts, one per planned slot, stopping at the
 * first failure.
 *
 * Partial success is the normal outcome, not an error: three posts written out
 * of five requested is three real posts plus an honest account of why the other
 * two are missing. The only case reported as an outright failure is a run that
 * produced NOTHING — there the caller learns exactly what a single generation
 * would have told it, with the same code, so the API answers identically
 * whether one post or five were asked for.
 */
export async function bulkGeneratePosts(
  slug: string,
  userId: string,
  isGlobalAdmin: boolean,
  input: BulkGeneratePostsInput,
  deps: BulkGeneratePostsDeps = {}
): Promise<BulkGeneratePostsResult> {
  const generate = deps.generate ?? generateDraftPost;
  const generateTopic = deps.generateTopic ?? generateTopicAcrossChannels;
  const newContentGroupId = deps.newContentGroupId ?? (() => crypto.randomUUID());
  const loadPostingWindows = deps.loadPostingWindows ?? loadPostingWindowsFromDb;
  const newBatchId = deps.newBatchId ?? (() => crypto.randomUUID());
  const auditLog = deps.auditLog ?? createAuditLog;
  const now = deps.now ?? Date.now;

  // ── Validate the request itself ───────────────────────────────────────────
  // Before any access check, because these are answers about the request, not
  // about the company — and they cost nothing to give.
  //
  // The rules live in `validate-bulk-request.service.ts` and are shared with the
  // enqueue path, which runs them synchronously so a malformed request is
  // refused with a 422 instead of becoming a job that fails in a worker log.
  // Repeated here — not skipped on the grounds that the route already asked —
  // because this service is reachable from the worker, and a payload that got
  // there by any other route must not be able to spend anything unchecked.
  const custom = input.customDistribution;
  const problem = await validateBulkRequest(slug, input, new Date(now()), {
    loadEnabledSourceIds: deps.loadEnabledSourceIds,
  });
  if (problem !== null) return asRequestFailure(problem);

  // The per-batch content mix, in the shape the scheduler's own mix module reads.
  const mixQuotas: MixQuota[] | null =
    input.sourceMix === undefined
      ? null
      : input.sourceMix.map((q) => ({ sourceId: q.sourceId, postsPerWeek: q.posts }));

  // Slots are planned up front because each post is persisted with its own
  // `scheduledFor` as it is written.
  //
  //   • Evenly — the dates bound the PERIOD and the channel's posting windows
  //     inside it decide the days and the times. Those are read from the database
  //     rather than taken from the request: the client previews with a copy of
  //     them, it does not get to set them.
  //   • Custom — the user chose every date and every time, already checked
  //     against that same period and against the clock. They are scheduled
  //     verbatim, and the windows are not loaded at all, because consulting them
  //     here could only move a post off the time the form promised.
  //
  // Multi-channel: EVERY CHANNEL PLANS ITS OWN, from its own posting windows, so
  // a topic's LinkedIn version can land at 09:00 and its Instagram version at
  // 18:00 — which is each channel's scheduling rule being honoured, not a
  // discrepancy. Custom mode is the deliberate exception: the user named the
  // times for the topic, so every channel version of it inherits the same one
  // and can be moved individually afterwards with the existing controls.
  const slotsByChannel = new Map<string, Date[]>();
  if (custom !== undefined) {
    const shared = planCustomSlots(custom);
    for (const channel of input.channels) slotsByChannel.set(channel, shared);
  } else {
    for (const channel of input.channels) {
      slotsByChannel.set(
        channel,
        planBulkSlots({
          startDate: input.startDate,
          endDate: input.endDate,
          count: input.numberOfPosts,
          postingWindows: await loadPostingWindows(slug, channel),
        })
      );
    }
  }

  // The topic-level timeline: what the batch's own progress is measured against,
  // and what a failure with no post to attach itself to is dated by. The first
  // channel's plan, because a topic is attempted in channel order.
  const slots = slotsByChannel.get(input.channels[0]) ?? [];

  const batchId = newBatchId();
  // Posts an earlier attempt committed. Counted in the summary from the start so
  // a resumed run reports the batch, not just the part of it that this attempt
  // happened to write.
  const posts: BulkGeneratedPost[] = [...(deps.resume?.posts ?? [])];
  const groups: BulkGeneratedGroup[] = [];
  const failures: BulkGenerationFailure[] = [];
  let stopReason: BulkStopReason | null = null;
  // Taken from the first post actually written rather than looked up: the batch
  // audit entry only exists when something was generated, and generation has
  // already resolved the company by then.
  let companyId: string | null = null;

  // Mix bookkeeping, all of it scoped to THIS run. `generatedBySource` is what
  // nextDueQuota measures a quota's progress against; `exhausted` is what makes
  // transferExhaustedQuotas hand a dry source's remaining posts to the sources
  // that can still write them. Neither is persisted — the saved mix is untouched
  // by anything that happens in this loop.
  const generatedBySource = new Map<string | null, number>();
  const exhausted = new Set<string | null>();
  const exhaustedSources: Array<string | null> = [];

  /**
   * The group for a topic index, created on first use.
   *
   * Upsert rather than push because a RESUMED topic already has a group — the
   * one an earlier attempt opened — and this attempt is adding the channels that
   * were missing, not starting a second group beside it.
   */
  const upsertGroup = (index: number, contentGroupId: string): BulkGeneratedGroup => {
    const existing = groups.find((g) => g.index === index);
    if (existing) return existing;
    const created: BulkGeneratedGroup = { index, contentGroupId, posts: [], failures: [] };
    groups.push(created);
    return created;
  };

  // Rebuild the groups an earlier attempt completed, so the summary describes the
  // whole batch rather than only this attempt's share of it.
  for (const p of deps.resume?.posts ?? []) {
    upsertGroup(p.index, p.contentGroupId).posts.push(p);
  }

  /**
   * The summary exactly as it stands, in the shape it will finally have.
   *
   * One shape for "running" and "finished" is deliberate: the UI polling a job
   * mid-flight and the UI reading a completed one parse the same object, so
   * there is no second progress format to keep in step with this one.
   */
  const buildSummary = (): BulkGenerationSummary => {
    const attemptedTopics = groups.length;
    return {
      batchId,
      requested: input.numberOfPosts,
      generated: groups.filter((g) => g.posts.length > 0).length,
      failed: input.numberOfPosts - groups.filter((g) => g.posts.length > 0).length,
      channels: [...input.channels],
      requestedPosts: input.numberOfPosts * input.channels.length,
      generatedPosts: posts.length,
      groups: groups.map((g) => ({ ...g, posts: [...g.posts], failures: [...g.failures] })),
      postIds: posts.map((p) => p.postId),
      posts: [...posts],
      failures: [...failures],
      notAttempted: Math.max(0, input.numberOfPosts - attemptedTopics),
      stoppedEarly: attemptedTopics < input.numberOfPosts,
      stopReason,
      exhaustedSources: [...exhaustedSources],
    };
  };

  /**
   * Hands the caller the summary so far. Best-effort by contract — a progress
   * write must never be the reason a batch of committed posts is lost — so
   * anything it throws is swallowed here rather than at each call site.
   */
  const reportProgress = async (
    topicIndex: number,
    contentGroupId: string | null,
    partial: TopicGenerationOutcome | null,
    scheduledFor: Date
  ): Promise<void> => {
    if (!deps.onProgress) return;
    // A topic mid-flight: fold what it has written so far into the summary the
    // caller sees, WITHOUT committing it to the run's own bookkeeping — the
    // topic's own bookkeeping happens once, when it finishes.
    const snapshot = buildSummary();
    if (partial && contentGroupId) {
      const live = partial.posts.map((p) => ({
        index: topicIndex,
        postId: p.postId,
        scheduledFor: p.scheduledFor ?? scheduledFor,
        channel: p.channel,
        contentGroupId,
      }));
      const seen = new Set(snapshot.postIds);
      const fresh = live.filter((p) => !seen.has(p.postId));
      snapshot.posts = [...snapshot.posts, ...fresh];
      snapshot.postIds = snapshot.posts.map((p) => p.postId);
      snapshot.generatedPosts = snapshot.posts.length;
      // The anchor rides along so a retry can resume THIS topic rather than
      // start a new one for the channels still missing.
      snapshot.liveTopic = {
        index: topicIndex,
        contentGroupId,
        anchor: partial.anchor,
        completedChannels: partial.posts.map((p) => p.channel),
      };
    }
    try {
      await deps.onProgress(snapshot);
    } catch (err) {
      console.warn(
        `[bulk-generate] Progress report failed (non-fatal): ${
          err instanceof Error ? err.message : String(err)
        }`
      );
    }
  };

  const minSlotBudgetMs = deps.minSlotBudgetMs ?? MIN_SLOT_BUDGET_MS;
  const deadline = createRequestDeadline(now() + (deps.softBudgetMs ?? BULK_SOFT_BUDGET_MS), now);

  // Everything below runs under the ambient deadline, so every outbound call the
  // generations make is bounded by the time left in THIS request. See
  // BULK_SOFT_BUDGET_MS for why a bulk run cannot be allowed to find out about
  // the function cap the hard way.
  const zeroGenerated = await runInRequestDeadline(deadline, async () => {
    /** The single-post answer for a run that wrote nothing at all. */
    const asSingleFailure = (result: GenerateDraftPostFailure) => ({
      success: false as const,
      code: result.code,
      message: result.message ?? DEFAULT_MESSAGES[classifyBulkFailure(result.code)],
      reason: result.reason,
      attempts: result.attempts,
      retryAfterMs: result.retryAfterMs,
    });

    // The last "nothing left to write from" a mix run hit. Kept because it is
    // the honest answer when every source runs dry before a single post exists:
    // the caller gets the generation's own code, exactly as it would from a
    // one-post request that found the same empty pool.
    let lastExhaustion: GenerateDraftPostFailure | null = null;

    /**
     * The longest a topic of THIS batch has actually taken, in ms.
     *
     * The gate below is calibrated from this rather than from a constant,
     * because a constant cannot know what a topic costs here: it is one LLM call
     * against a hosted provider with images off, and several minutes per channel
     * against a self-hosted image worker — and it scales with the number of
     * channels the batch asked for, which the constant never saw.
     *
     * The maximum rather than the most recent: one cheap topic does not make the
     * next one cheap, and the question being asked is "could a topic like the
     * ones I have seen still fit", where the expensive one is the honest answer.
     *
     * Measured around the WHOLE slot, so it includes a mix run's re-attempts
     * against the next source when one turns out to be dry — those are part of
     * what filling a slot costs. Failed topics count too: a failure that took two
     * minutes of LLM retries is evidence about cost just as much as a success is.
     */
    let observedSlotMs = 0;

    for (let i = 0; i < slots.length; i++) {
      const scheduledFor = slots[i];
      const topicIndex = i + 1;

      // Channels an earlier attempt already committed for this topic. A resumed
      // run writes only the remainder, so nothing is generated twice.
      const alreadyGenerated = deps.resume?.completedChannels[topicIndex] ?? [];
      const remainingChannels = input.channels.filter((c) => !alreadyGenerated.includes(c));
      if (remainingChannels.length === 0) continue;

      // Never start a topic there is not enough time left to FINISH — measured
      // against what a topic of this batch has actually cost, not against a
      // guess. Starting one that cannot finish is what loses images (see
      // MIN_SLOT_BUDGET_MS). The first slot is always attempted, so a run can
      // never report "no time" without having tried at all.
      if (i > 0 && remainingBudgetMs() < Math.max(observedSlotMs, minSlotBudgetMs)) {
        stopReason = "time_budget";
        break;
      }

      const slotStartedAt = now();

      // Fill this one slot.
      //
      // Without a mix that is a single attempt, exactly as before. With one, a
      // slot may be attempted more than once: a source that turns out to have
      // nothing left is marked spent for the rest of the run and its remaining
      // posts pass to the sources that can still write them (nextDueQuota reads
      // the post-transfer quotas), so the slot is retried against whichever
      // source is due next rather than costing the batch a post. Every other
      // kind of failure still ends the run at the first one — see
      // classifyBulkFailure for why retrying those cannot help.
      let stop = false;

      while (!stop) {
        const due =
          mixQuotas === null
            ? null
            : nextDueQuota({ quotas: mixQuotas, generatedBySource, exhausted });

        // Mix runs only: every quota is filled or spent, so there is nothing
        // left to write this slot — or any slot after it — from.
        if (mixQuotas !== null && due === null) {
          if (posts.length === 0 && lastExhaustion !== null) {
            return asSingleFailure(lastExhaustion);
          }
          stopReason = "mix_exhausted";
          stop = true;
          break;
        }

        // The one and only generation path. One call per TOPIC, which fans out
        // to one `generateDraftPost` per channel — the same call the single-post
        // route makes, with the same options, plus this topic's slots, batch id
        // and group id. A mix topic differs only in WHICH source it names, and it
        // names it the same way the dropdown would.
        //
        // The content group id comes from the resume state when this topic
        // already has one, so a retry continues that group rather than opening a
        // second one beside it.
        const contentGroupId = deps.resume?.contentGroupIds[topicIndex] ?? newContentGroupId();

        const outcome = await generateTopic(
          {
            slug,
            userId,
            isGlobalAdmin,
            contentGroupId,
            channels: remainingChannels,
            scheduledFor: Object.fromEntries(
              input.channels.map((c) => [c, slotsByChannel.get(c)?.[i] ?? scheduledFor])
            ),
            generationBatchId: batchId,
            contentSource: due === null ? input.contentSource : contentSourceForQuota(due.sourceId),
            contentSourceId: due === null ? undefined : due.sourceId,
            contentLanguage: input.contentLanguage,
            includeSourceLinkOverride: input.includeSourceLinkOverride,
            autoGenerateImageOverride: input.autoGenerateImageOverride,
            llmConfigId: input.llmConfigId,
            // The topic an earlier attempt settled on, so the channels still
            // missing continue THAT story instead of each choosing a new one.
            anchor: deps.resume?.anchors[topicIndex] ?? null,
          },
          {
            generate,
            // Surfaces the anchor to the caller the moment it exists, which is
            // what a retry needs to resume this very topic.
            onChannelComplete: async (partial) => {
              await reportProgress(topicIndex, contentGroupId, partial, scheduledFor);
            },
          }
        );

        const topicFailures: BulkGenerationFailure[] = outcome.failures.map((f) => ({
          index: topicIndex,
          scheduledFor: slotsByChannel.get(f.channel)?.[i] ?? scheduledFor,
          code: f.code,
          reason: classifyBulkFailure(f.code),
          message: f.message,
          channel: f.channel,
          // The generator's own diagnostics, carried through unchanged so a
          // failed channel inside a partial batch explains itself as fully as a
          // failed single generation does.
          uniquenessReason: f.reason,
          attempts: f.attempts,
          retryAfterMs: f.retryAfterMs,
        }));

        // At least one channel version exists, so the TOPIC succeeded. A group
        // that is short a channel is a partial group, reported as such — not a
        // reason to abandon the batch or to discard the posts that do exist.
        if (outcome.posts.length > 0) {
          const written = outcome.posts.map((p) => ({
            index: topicIndex,
            postId: p.postId,
            scheduledFor: p.scheduledFor ?? scheduledFor,
            channel: p.channel,
            contentGroupId,
          }));
          posts.push(...written);
          // Carried out of the topic rather than looked up: the generations that
          // just committed have already resolved the company, so the batch's
          // audit entry is written against the same one its posts landed in.
          companyId ??= outcome.companyId;
          groups.push({
            index: topicIndex,
            contentGroupId,
            posts: written,
            failures: topicFailures,
          });
          failures.push(...topicFailures);
          if (due !== null) {
            generatedBySource.set(due.sourceId, (generatedBySource.get(due.sourceId) ?? 0) + 1);
          }
          break;
        }

        // Nothing at all was written for this topic. Every channel failed, so
        // the topic's outcome is the outcome they agree on — read from the first,
        // which is also the one that tried to claim a source.
        const firstFailure = outcome.failures[0];
        if (!firstFailure) break;

        // This source is spent — for EVERY channel, which is what makes it a
        // property of the source rather than of one attempt. Not a failure of
        // the topic: the posts it owed move to the sources that still have
        // material, and this topic is tried again against the next one due.
        if (
          due !== null &&
          outcome.failures.every((f) => classifyBulkFailure(f.code) === "no_eligible_content")
        ) {
          exhausted.add(due.sourceId);
          exhaustedSources.push(due.sourceId);
          // The failure itself, not a copy of two of its fields — it is what the
          // caller is answered with if the whole run ends up empty.
          lastExhaustion = firstFailure;
          continue;
        }

        // Nothing was written at all, in the whole run: answer exactly as the
        // single-post flow would, so the caller gets the real code — and the
        // retry hints that came with it — rather than a "successful batch of
        // zero". `firstFailure` IS a GenerateDraftPostFailure, so passing it on
        // preserves every diagnostic the generator attached.
        if (posts.length === 0) {
          return asSingleFailure(firstFailure);
        }

        failures.push(...topicFailures);
        groups.push({ index: topicIndex, contentGroupId, posts: [], failures: topicFailures });
        stopReason = "generation_failed";
        stop = true;
      }

      // Recorded before the progress write and before `break` can skip it, so a
      // topic that ended the run still contributes what it cost.
      observedSlotMs = Math.max(observedSlotMs, now() - slotStartedAt);

      await reportProgress(topicIndex, null, null, scheduledFor);
      if (stop) break;
    }

    return null;
  });

  if (zeroGenerated !== null) return zeroGenerated;

  // One summary, built by the same function that built every progress snapshot,
  // so a caller that watched the run and a caller that only read the end are
  // never looking at two different accounts of it.
  const summary = buildSummary();

  if (summary.generated < input.numberOfPosts) {
    console.warn(
      `[bulk-generate] Batch ${batchId} produced ${summary.generated}/${input.numberOfPosts} topics ` +
        `(${summary.generatedPosts}/${summary.requestedPosts} posts across ${input.channels.length} channel(s))` +
        (failures.length > 0
          ? ` — stopped at topic ${failures[0].index}: ${failures[0].code}`
          : stopReason === "time_budget"
            ? " — stopped: request time budget exhausted"
            : stopReason === "mix_exhausted"
              ? " — stopped: every source in the content mix ran out of material"
              : "")
    );
  }

  // One entry for the whole request, beside the per-post POST_GENERATED entries
  // generation already writes. Those record what each post is; this records the
  // decision that produced them — how many were asked for, over which period,
  // how they were distributed, and where the run stopped if it did. Without it
  // the batch id in the posts table has nothing explaining what it refers to,
  // and a partial run leaves no trace at all once the HTTP response is gone.
  if (companyId !== null) {
    await auditLog({
      companyId,
      userId,
      action: AUDIT_ACTIONS.POST_BULK_GENERATED,
      entityType: "post_batch",
      entityId: batchId,
      metadata: {
        // Every channel each topic was written for. `channel` (singular) is kept
        // alongside it for a single-channel batch so existing log readers — and
        // every entry already in the table — still mean the same thing.
        channels: [...input.channels],
        channel: input.channels.length === 1 ? input.channels[0] : null,
        requested: input.numberOfPosts,
        generated: summary.generated,
        failed: input.numberOfPosts - summary.generated,
        // The Post rows behind those topics, which is the number that explains
        // the LLM spend when several channels were selected.
        requestedPosts: summary.requestedPosts,
        generatedPosts: summary.generatedPosts,
        contentGroupIds: summary.groups.map((g) => g.contentGroupId),
        distribution: custom !== undefined ? "custom" : "even",
        startDate: input.startDate,
        endDate: input.endDate,
        // The window the batch actually occupies, which is what a reader wants
        // when asking "what did this click put on the calendar?".
        firstScheduledFor: posts[0]?.scheduledFor.toISOString() ?? null,
        lastScheduledFor: posts[posts.length - 1]?.scheduledFor.toISOString() ?? null,
        stopReason,
        failureCode: failures[0]?.code ?? null,
        postIds: posts.map((p) => p.postId),
        // The mix this ONE run used, recorded because it may differ from the
        // company's saved default — which this run did not change. Without it
        // the log could not explain why these posts came from these sources.
        sourceMix: input.sourceMix ?? null,
        exhaustedSources,
      },
    });
  }

  return { success: true, data: summary };
}
